Repository AdobeDocs/commerce-marketplace, pull requests merged in 2022-08, with the labels that each got.

#35 DevPortal - "users" API updated with Adobe Id / IMS
  src/pages/guides/eqp/v1/users.md
Labels: major update, 2.4.5

#38 Replace obsolete devdocs links
  src/pages/guides/sellers/extension-create.md
  src/pages/guides/sellers/installation-and-varnish-tests.md
  src/pages/guides/sellers/seller-overview.md
  src/pages/guides/sellers/submit-for-technical-review.md
  src/pages/guides/sellers/technical-reference.md
  src/pages/guides/sellers/technical-review-guidelines.md
  src/pages/guides/sellers/themes.md
Labels: migration

#36 [DevP][IMS] update DevDocs for DevPortal for AdobeUserId/AdobeOrgId
  src/pages/guides/sellers/_images/access-keys.png
  src/pages/guides/sellers/_images/account-information.png
  src/pages/guides/sellers/_images/basic-access-key-information.png
  src/pages/guides/sellers/profile-information.md
Labels: major update
