Repository AdobeDocs/commerce-marketplace, pull requests merged in 2023-10, with the labels that each got.

#106 DevPortal updates to the "sellers" guide
  src/pages/guides/sellers/_images/submit-new-version-detail.png
  src/pages/guides/sellers/_images/themes.png
  src/pages/guides/sellers/_images/your-shared-packages.png
  src/pages/guides/sellers/app-version.md
  src/pages/guides/sellers/apps.md
  src/pages/guides/sellers/developer-portal.md
  src/pages/guides/sellers/extension-version.md
  src/pages/guides/sellers/extensions.md
  src/pages/guides/sellers/shared-packages.md
  src/pages/guides/sellers/themes.md
Labels: editorial, internal

#104 App Assurance Program
  src/data/navigation/sections/guides.js
  src/pages/guides/sellers/_images/assurance-badge.png
  src/pages/guides/sellers/assurance.md
Labels: new topic

#107 Merge `develop` to `main`
  src/data/navigation/sections/guides.js
  src/pages/guides/sellers/_images/assurance-badge.png
  src/pages/guides/sellers/assurance.md
Labels: major update, new topic

#108 Rename the test:links task
  package.json
Labels: enhancement, maintenance
