Repository AdobeDocs/commerce-marketplace, pull requests merged in 2024-06, with the labels that each got.

#130 AC-12103: Marketplace Help Center
  src/data/navigation/sections/guides.js
  src/pages/guides/eqp/v1/index.md
  src/pages/guides/sellers/account-setup-process.md
  src/pages/guides/sellers/branding.md
  src/pages/guides/sellers/developer-register.md
  src/pages/guides/sellers/faq.md
  src/pages/guides/sellers/installation-and-varnish-tests.md
  src/pages/guides/sellers/profile-information.md
  src/pages/guides/sellers/review-report.md
  src/pages/guides/sellers/sales.md
  src/pages/index.md
Labels: major-update, internal

#129 COMDOX-959: Remove beta note
  src/pages/guides/sellers/assurance.md
Labels: editorial, internal

#132 Upgrade theme to v4.11.14
  .remarkrc.mjs
  package.json
  src/pages/guides/sellers/developer-register.md
  src/pages/guides/sellers/sales.md
  src/pages/index.md
  yarn.lock
Labels: dependencies, internal
