Repository AdobeDocs/commerce-marketplace, pull requests merged in 2024-07, with the labels that each got.

#131 AC-12104: Replaced marketplace support contact
  .remarkrc.mjs
  src/pages/guides/sellers/copy-paste-detector.md
  src/pages/guides/sellers/developer-portal.md
  src/pages/guides/sellers/faq.md
  src/pages/guides/sellers/installation-and-varnish-tests.md
  src/pages/guides/sellers/malware-scan.md
  src/pages/guides/sellers/semantic-version-check.md
  src/pages/guides/sellers/submit-for-marketing-review.md
  src/pages/guides/sellers/subscriptions/buying-subscriptions.md
  src/pages/guides/sellers/subscriptions/extension-subscriptions.md
  src/pages/guides/sellers/subscriptions/selling-subscriptions.md
Labels: editorial, internal

#136 Imgbot
  src/pages/guides/eqp/_images/sandbox-access-key-create.png
  src/pages/guides/eqp/_images/sandbox-access-key-empty.png
  src/pages/guides/eqp/_images/sandbox-access-key-list.png
  src/pages/guides/eqp/_images/sandbox-landing-page.png
  src/pages/guides/eqp/_images/sandbox-not-eligible.png
  src/pages/guides/sellers/_images/abandoned-cancelled.png
  src/pages/guides/sellers/_images/abandoned-delisted.png
  src/pages/guides/sellers/_images/access-keys.png
  src/pages/guides/sellers/_images/account-information.png
  src/pages/guides/sellers/_images/app-save-new-version.png
  src/pages/guides/sellers/_images/apps-prep.svg
  src/pages/guides/sellers/_images/assurance-badge.png
  src/pages/guides/sellers/_images/basic-access-key-information.png
  src/pages/guides/sellers/_images/developer-portal.png
  src/pages/guides/sellers/_images/marketing-compatibility.png
  src/pages/guides/sellers/_images/marketing-description2.png
  src/pages/guides/sellers/_images/marketing-description3.png
  src/pages/guides/sellers/_images/marketing-images1.png
  src/pages/guides/sellers/_images/marketing-images2.png
  src/pages/guides/sellers/_images/marketing-images3.png
  src/pages/guides/sellers/_images/marketing-pricing1.png
  src/pages/guides/sellers/_images/marketing-submission-additional-details.png
  src/pages/guides/sellers/_images/marketing-submission-documentation.png
  src/pages/guides/sellers/_images/marketing-submission-list.png
  src/pages/guides/sellers/_images/marketing-submission-pricing.png
  src/pages/guides/sellers/_images/marketing-submission-support.png
  src/pages/guides/sellers/_images/marketplace-profile.png
  src/pages/guides/sellers/_images/obsolete-cancelled.png
  src/pages/guides/sellers/_images/obsolete-delisted.png
  src/pages/guides/sellers/_images/partner-apps.png
  src/pages/guides/sellers/_images/release-delisted.png
  src/pages/guides/sellers/_images/submit-chart1.png
  src/pages/guides/sellers/_images/submit-new-version-detail.png
  src/pages/guides/sellers/_images/subscriptions-buying-pricing.png
  src/pages/guides/sellers/_images/subscriptions-cancel.png
  src/pages/guides/sellers/_images/subscriptions-confirm-remove.png
  src/pages/guides/sellers/_images/subscriptions-payment-methods.png
  src/pages/guides/sellers/_images/subscriptions-pricing-model.png
  src/pages/guides/sellers/_images/subscriptions-remove-from-store.png
  src/pages/guides/sellers/_images/subscriptions-remove-replace.png
  src/pages/guides/sellers/_images/tax-forms.png
  src/pages/guides/sellers/_images/technical-submission-details1.png
  src/pages/guides/sellers/_images/technical-submission-details2.png
  src/pages/guides/sellers/_images/technical-submission-docs.png
  src/pages/guides/sellers/_images/technical-submission-rnotes.png
  src/pages/guides/sellers/_images/technical-submission-shared.png
  src/pages/guides/sellers/_images/terms-of-service.png
  src/pages/guides/sellers/_images/test-reports.png
  src/pages/guides/sellers/_images/themes.png
  src/pages/guides/sellers/_images/your-apps.png
  src/pages/guides/sellers/_images/your-extensions.png
  src/pages/guides/sellers/_images/your-shared-packages.png
Labels: maintenance

#138 Upgrade devDependencies
  .remarkrc.mjs
  package.json
  yarn.lock
Labels: dependencies

#139 Enable indexing on deploy
  .github/workflows/index.yml
  .github/workflows/publish.yml
Labels: maintenance, internal
